### ISSUE TITLE
PHP7 oink oink

### ISSUE THREAD

**Issue by DogTimeNsk** [parf/spartan-test#2]
https://github.com/parf/spartan-test/blob/eee158479d558eb8989a1eb9255562cf9da2e2ba/src/STest.php#L654

https://github.com/parf/spartan-test/blob/eee158479d558eb8989a1eb9255562cf9da2e2ba/src/STest.php#L681

https://github.com/parf/spartan-test/blob/eee158479d558eb8989a1eb9255562cf9da2e2ba/src/STest.php#L707

https://github.com/parf/spartan-test/blob/eee158479d558eb8989a1eb9255562cf9da2e2ba/src/STest.php#L731

https://github.com/parf/spartan-test/blob/eee158479d558eb8989a1eb9255562cf9da2e2ba/src/STest.php#L911

**Comment by parf** [comment]
fixed
